const ROLES = {
  USER: "USER",
  ADMIN: "ADMIN",
};

const USER_STATUSES = {
  ACTIVE: "ACTIVE",
  BANNED: "BANNED",
};

const SKILL_LEVELS = ["BEGINNER", "INTERMEDIATE", "ADVANCED", "EXPERT"];

const MATCH_STATUSES = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
};

const SESSION_STATUSES = {
  SCHEDULED: "SCHEDULED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

const REPORT_STATUSES = {
  PENDING: "PENDING",
  RESOLVED: "RESOLVED",
  REJECTED: "REJECTED",
};

const REPORT_REASONS = ["Spam", "Fake Profile", "Abusive Behavior", "Other"];

const NOTIFICATION_TYPES = {
  MATCH_REQUEST: "MATCH_REQUEST",
  MATCH_ACCEPTED: "MATCH_ACCEPTED",
  MATCH_REJECTED: "MATCH_REJECTED",
  SESSION_SCHEDULED: "SESSION_SCHEDULED",
  REVIEW_ADDED: "REVIEW_ADDED",
  NEW_MESSAGE: "NEW_MESSAGE",
  SYSTEM: "SYSTEM",
};

module.exports = {
  ROLES,
  USER_STATUSES,
  SKILL_LEVELS,
  MATCH_STATUSES,
  SESSION_STATUSES,
  REPORT_STATUSES,
  REPORT_REASONS,
  NOTIFICATION_TYPES,
};
